# Repaso Estadística Descriptiva e Inferencial

## Estadística Descriptiva

### Esperanza

La esperanza por definición es el promedio de los resultados de un experimento si aquel lo repetimos muchas veces. Matemáticamente la esperanza para una v.a.d es:

$$
E[X] = \sum_{i=1}^{\n} x_iP(X=x_i)
$$

En resumidas cuentas, es la suma de la multiplicación de la observación por su probabilidad. Por ejemplo, si estuviésemos interesados en calcular la esperanza de lanzar un dado honesto, primero, sabemos que:

|$X$|$P(X = x_i)$|$XP(X = x_i)$ |
|-|----------|----|
|1| 1/6 | 1/6 |
|2| 1/6 | 2/6 |
|3| 1/6 | 3/6 |
|4| 1/6 | 4/6 |
|5| 1/6 | 5/6 |
|6| 1/6 | 6/6 |

Al sumar las multiplicaciones de las observaciones por su probabilidad obtendremos la esperanza, por lo tanto, para este caso la esperanza es:

$$
E[X] = \frac{1+2+3+4+5+6}{6} = \frac{21}{6} = 3.5
$$

### Varianza

Sea $X_1, X_2, X_3, ... , X_n$ una variable aleatoria i.i.d. con media $\mu$ y varianza $\sigma^2$ definición la varianza se puede escribir como:

$$
V(X) = \sum_{i = 1}^n \frac{(x_i -\mu)^2}{n}
$$

Pero, podemos escribir la varianza como esperanza, tal que:

$$
V(X) = E[(X - \mu)^2]
$$
$$
V(X) = E[X^2 - 2X\mu + \mu^2]
$$
$$
V(X) = E[X^2] - 2\mu E[X] + \mu^2
$$
$$
V(X) = E[X^2] - 2\mu^2 + \mu^2
$$
$$
V(X) = E[X^2] - \mu^2
$$
$$
V(X) = E[X^2] - (E[X])^2
$$







