# Modelo de Regresión Lineal Múltiple

## Definición

A diferencia de un modelo de Regresión Lineal Simple, el modelo de Regresión Lineal Múltiple permite estudiar el impacto de $k$ variables regresoras $X$ en una variable regresada $Y$. Inicialmente tenemos que:

\[
\begin{bmatrix}
    Y_1 \\
    Y_2 \\
    \vdots \\
    Y_n
\end{bmatrix}
=
\begin{bmatrix}
    1 & x_{11} & x_{12} \\
    1 & x_{21} & x_{22} \\
    \vdots & \vdots & \vdots \\
    1 & x_{n1} & x_{n2}
\end{bmatrix}
\begin{bmatrix}
    \beta_0 \\
    \beta_1 \\
    \vdots \\
    \beta_{k-1}
\end{bmatrix}
+
\begin{bmatrix}
    \varepsilon_1 \\
    \varepsilon_2 \\
    \vdots \\
    \varepsilon_n
\end{bmatrix}
\]

Donde la matriz de $Y's$ es de orden $\mathbb{M}_{n\times 1}$, la matriz de $\varepsilon's$ es de orden $\mathbb{M}_{n\times 1}$, la matriz de $\beta's$ es de orden $\mathbb{M}_{k\times 1}$ y la matriz de covariadas es de orden $\mathbb{M}_{n\times k}$. Finalmente, de manera formal definimos el modelo de regresión múltiple tal que:

$$
Y = X\beta + \xi
$$

Donde tenemos que el estimador para la matriz de parámetros es la siguiente:

$$\hat{\beta} = (X^TX)^{-1}X^TY$$

Y la varianza del estimador es:

$$Var(\beta|X) = \sigma^2(X^TX)^{-1}$$

Donde la varianza del vector de estimaciones se construye en base al supuesto de Homocedasticidad. (Véase la demostración de ambas en el Anexo)

## Bondad de Ajuste

### $R^2$

La bondad de ajuste mide simplemente que porcentaje de la variabilidad de la variable regresada es explicada por la o las variables regresoras. Esto se mide a través del $R^2$. Como nota, no hay que obsesionarse con esto ya que, solamente representa lo mencionado en la definición y no así la robustez del modelo (un $R^2$ alto da una falsa sensación de robustez). El $R^2$ se obtiene de la siguiente manera:

$$
R^2 = \frac{SCE}{SCT} = 1- \frac{SCR}{SCT}
$$

Donde $R^2 \in \{0,1\}$. Usando la siguiente relación: $SCT = SCE + SCR$, si el modelo se ajusta perfectamente, es decir, $SCR = 0$, entonces el $R^2 = 1$. De lo contrario, si el modelo no se ajusta de ninguna manera $SCE = 0$, entonces el $R^2 = 0$. 

El $R^2$ se interpreta como: El modelo logra capturar un $R^2\%$ de la variabilidad de $Y$.

### Overfitting

También, otra de las razones por las cuales no obsesionarse con el $R^2$ es por el **overfitting**. El overfitting es simplemente el acto de incluir variables inexplicativas a un modelo, generando relaciones espurias. Esto podría ''inflar'' el $R^2$, concluyendo un ajuste que sobredimensiona el ajuste real. Suponga que que tenemos el siguiente modelo poblacional (que claro, no conocemos):

$$
Y = \gamma_0 + \gamma_1X_1 + \gamma_2X_2 + u
$$

Donde este modelo tiene un $R^2 = 0.7$. En teoría, intentando estimar este mismo modelo, el máximo $R^2$ que podemos ostentar sería uno igual a $0.8$. Ahora, imaginemos que este fue el modelo que estimamos:

$$
Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \beta_3X_3 + \varepsilon
$$

Con un ''impresionante'' $R^2 = 0.8$. En este caso estamos sobreajustando el modelo, incluyendo una variable que genera una relación espuria con la variable regresada.

## Inferencia Estadística

Para esta sección, utilizaremos la misma manera de realizar pruebas de significancia individual que en el capítulo de \textit{Regresión Lineal Simple}. Ahora, añadiremos 3 pruebas de hipótesis importantes para analizar un modelo.

### Prueba de Significancia Global

La prueba de hipótesis global tiene por premisa ver si todos los parámetros son significativos en conjunto a nivel poblacional. Por ende, la notación en este caso es la siguiente:

$$H_0: \beta_1 = \beta_2 = ... = \beta_k = 0$$
$$H_A: \text{Al menos uno de los $\beta$ es distinto de 0.}$$

En este caso utilizaremos nuevamente el método del valor crítico, pero, en este caso nuestro estadístico de prueba distribuye en una distribución F de Snedecor. Nuestro estadístico de prueba es el siguiente:

$$
F_c = \frac{R^2/k}{(1-R^2)/(n-k-1)}
$$

Donde compararemos este estadístico con un valor crítico $F$, que depende de los grados de libertad del numerador y grados de libertad del denominador, y, la manera de comparar es la misma: Si $F_c > F_{df1,df2}$ (donde $df1 = k$ y $df2 = n-k-1$) entonces existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, los parámetros son significativos en conjunto.

## Prueba de Significancia de Combinaciones de Parámetros

Inicialmente hemos hecho pruebas de hipótesis para significancia individual de un solo parámetro. Pero, también nos interesaría estudiar por ejemplo si los efectos de dos variables son iguales, es decir $\beta_1 = \beta_2$. En este caso la idea cambia un poco, pues, tenemos que realizar ciertas transformaciones para hacer el proceso más sencillo. La notación para este ejemplo sería:

\begin{center}
    $H_0: \beta_1 - \beta_2 = 0$\\
    $H_A = \beta_1 - \beta_2 \ne 0$
\end{center}

Y así, tenemos que obtener un estadístico $t_c$ el cual obtenemos derivando de la mísma fórmula de la prueba de hipótesis individual pero cambiando ciertas cosas:

$$
t_c = \frac{(\widehat{\beta_1} - \widehat{\beta_2}) - \beta_{H_0}}{\sqrt{Var(\widehat{\beta_1} - \widehat{\beta_2})}}
$$

Donde luego, haremos la misma comparación, con los mismos valores de la distribución $t$ o de una distribución normal estándar mediante TLC.

## Múltiples Restricciones Lineales

Ya hemos realizado distintos tipos de prueba de hipótesis, pero, de todas maneras también querríamos estudiar si es que varias restricciones se cumplen a la vez, es decir algo de este estilo:

$$H_0:\beta_1 + \beta_3 = 3$$
$$\frac{1}{3}\beta_1 + \beta_2 = 4$$
$$H_1 = \text{Al menos una de las restricciones no se cumple}$$

Entonces no podemos hacer una prueba de hipótesis con un estadístico t normal, si no más bien, vamos a estimar un modelo (a través de MCO) en donde SI SE CUMPLAN estas restricciones. Entonces sea el modelo acorde al ejemplo definido como $Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \beta_3X_3 + \varepsilon$ Vamos a armar una matriz $R\beta = q$ donde R son los coeficientes de los betas bajo la hipótesis nula, $\beta$ nuestro vector de betas y $q$ el lado derecho del igual de nuestras hipótesis nulas. Entonces definimos:

$$
R = \begin{pmatrix}
    0 & 1 & 0 & 1 \\
    0 & \frac{1}{3} & 1 & 0
\end{pmatrix}
$$

$$
q = \begin{pmatrix}
    3 \\
    4
\end{pmatrix}
$$

y planteamos el problema que deseamos resolver:

 $$\text{min}: U^TU$$
 $$\text{s.a}: R\beta = q$$

Y sabemos que $U^TU = [Y - X\beta]^T[Y - X\beta]$.

Por lo tanto resolveremos el problema de minimización a través de multiplicadores de Lagrange, entonces el Lagrangeano nos queda:

$$
\mathcal{L} = [Y - X\beta]^T[Y - X\beta] + 2\lambda[R\beta-q]
$$

Y por tanto, para resolver se debe cumplir que:

 $$\frac{\partial\mathcal{L}}{\partial\lambda} = 0 \land \frac{\partial\mathcal{L}}{\partial\beta} = 0$$

La primera ecuación corresponde a la restricción, y la segunda ecuación correspondería a:


$$2(X^TX)\beta - 2X^TY + 2R^T\lambda = 0$$

Finalmente, desarrollando esto (véase en el Anexo) nuestro estimador de este modelo con las restricciones impuestas, al cual llamaremos \textbf{Mínimos Cuadrados Restringidos} es el siguiente:

$$
\widetilde{\beta} = (X^TX)^{-1}X^TY - (X^TX)^{-1}R^T\lambda
$$

Si nosotros deseamos calcular la varianza del estimador, tenemos lo siguiente:

$$
V(\widetilde{\beta}) = V(\widehat{\beta}) - \textbf{terminos positivos}
$$

Podemos ver entonces que, la varianza del estimador de MCR es menor a la de MCO \textbf{siempre y cuando las restricciones NO SE CUMPLAN}, en el caso contrario, la varianza de MCR y la varianza de MCO son iguales.

Luego de esto, derivando obtenemos que:

$$
\widetilde{\xi}^T\widetilde{\xi} = \widehat{\xi}^T\widehat{\xi} + (\widetilde{\beta} - \widehat{\beta})^TX^TX- 2(\widetilde{\beta} - \widehat{\beta})^TX^T\widehat{\xi}
$$

Concluyendo entonces que:

$$
\widetilde{\xi}^T\widetilde{\xi} \ge \widehat{\xi}^T\widehat{\xi}
$$

Por lo tanto, así $F_c = \frac{(\widetilde{\xi}^T\widetilde{\xi} - \widehat{\xi}^T\widehat{\xi})/q}{\widehat{\xi}^T\widehat{\xi}/(n-k)}$. Y amplificando por $\frac{1}{SCT}$ tenemos que:

$$
F_c = \frac{(R^2 - R^2_{r})/q}{(1-R^2)/(n-k-1)}
$$

Donde $q$ es el número de restricciones.

La conclusión es que, si $F_c > F_{df1,df2}$ (donde $df1 = q$ y $df2 = n-k-1$) entonces existe suficiente evidencia estadística para rechazar la hipótesis nula, es decir, las restricciones no se cumplen.