# Anexo

## Regresión Lineal Simple

### Demostración del estimador de $\hat{\beta}_0$ y $\hat{\beta}_1$ mediante MCO

$$
\text{Problema:} \quad \min_{\beta_0, \beta_1} \sum_{i=1}^{n}\varepsilon_i^2 = \sum_{i=1}^{n} (y_i - \beta_0 - \beta_1 x_i)^2
$$

**Para $\hat{\beta}_0$:**

$$
\frac{\partial \sum_{i=1}^{n} (y_i - \beta_0 - \beta_1 x_i)^2}{\partial \beta_0} = 0
$$

$$
-2\sum_{i=1}^{n} (y_i - \beta_0 - \beta_1 x_i) = 0
$$

$$
\sum_{i=1}^{n} y_i - n\beta_0 - \beta_1 \sum_{i=1}^{n} x_i = 0
$$

$$
n\beta_0 = \sum_{i=1}^{n} y_i - \beta_1 \sum_{i=1}^{n} x_i
$$

$$
\widehat{\beta}_0 = \frac{1}{n} \sum_{i=1}^{n} y_i - \hat{\beta}_1 \frac{1}{n} \sum_{i=1}^{n} x_i
$$

$$
\widehat{\beta}_0 = \bar{y} - \widehat{\beta}_1\bar{x}
$$

**Luego, para $\hat{\beta}_1$:**

$$
\frac{\partial \sum_{i=1}^{n} (y_i - \beta_0 - \beta_1 x_i)^2}{\partial \beta_1} = 0
$$

$$
-2\sum_{i=1}^{n} x_i (y_i - \beta_0 - \beta_1 x_i) = 0
$$

$$
\sum_{i=1}^{n} x_i y_i - \beta_0 \sum_{i=1}^{n} x_i - \beta_1 \sum_{i=1}^{n} x_i^2 = 0
$$

Sabiendo que $\hat{\beta}_0 = \bar{y} - \hat{\beta}_1\bar{x}$, podemos sustituirlo en la ecuación anterior:

$$
\sum_{i=1}^{n} x_i y_i - (\bar{y} - \hat{\beta}_1\bar{x}) \sum_{i=1}^{n} x_i - \hat{\beta}_1 \sum_{i=1}^{n} x_i^2 = 0
$$

$$
\sum_{i=1}^{n} x_i y_i - \bar{y} \sum_{i=1}^{n} x_i + \hat{\beta}_1\bar{x} \sum_{i=1}^{n} x_i - \hat{\beta}_1 \sum_{i=1}^{n} x_i^2 = 0
$$

Reordenando los términos con $\hat{\beta}_1$:

$$
\sum_{i=1}^{n} x_i y_i - \bar{y} \sum_{i=1}^{n} x_i = \hat{\beta}_1 \left( \sum_{i=1}^{n} x_i^2 - \bar{x} \sum_{i=1}^{n} x_i \right)
$$

Despejando $\hat{\beta}_1$:

$$
\hat{\beta}_1 = \frac{\sum_{i=1}^{n} x_i y_i - \bar{y} \sum_{i=1}^{n} x_i}{\sum_{i=1}^{n} x_i^2 - \bar{x} \sum_{i=1}^{n} x_i}
$$

Dividiendo numerador y denominador por $n$ y asumiendo datos i.i.d.:

$$
\hat{\beta}_1 = \frac{Cov(Y,X)}{Var(X)}
$$

---

### Demostración de Insesgadez para $\hat{\beta}_0$ y $\hat{\beta}_1$

**Primero, para $\hat{\beta}_0$:**

$$
E[\hat{\beta}_0] = E[\bar{y} - \hat{\beta}_1\bar{x}]
$$

$$
E[\hat{\beta}_0] = E[\bar{y}] - \bar{x}E[\hat{\beta}_1]
$$

Sabemos que $\bar{y} = \beta_0 + \beta_1\bar{x} + \bar{\varepsilon}$, entonces:

$$
E[\hat{\beta}_0] = E[\beta_0 + \beta_1\bar{x} + \bar{\varepsilon}] - \bar{x}E[\hat{\beta}_1]
$$

Por esperanza condicional cero, $E[\bar{\varepsilon}] = 0$:

$$
E[\hat{\beta}_0] = \beta_0 + \beta_1\bar{x} - \bar{x}E[\hat{\beta}_1]
$$

Dado que $E[\hat{\beta}_1] = \beta_1$:

$$
E[\hat{\beta}_0] = \beta_0 + \beta_1\bar{x} - \beta_1\bar{x} = \beta_0
$$

**Luego, para $\hat{\beta}_1$:**

$$
E[\hat{\beta}_1] = E\left[\frac{Cov(Y,X)}{Var(X)}\right]
$$

Dado que $Y = \beta_0 + \beta_1X + \varepsilon$:

$$
E[\hat{\beta}_1] = E\left[\frac{Cov(\beta_0 + \beta_1X + \varepsilon, X)}{Var(X)}\right]
$$

Por propiedades de la covarianza:

$$
E[\hat{\beta}_1] = E\left[\frac{Cov(\beta_1X, X) + Cov(\varepsilon, X)}{Var(X)}\right]
$$

Por exogeneidad estricta, $Cov(\varepsilon, X) = 0$:

$$
E[\hat{\beta}_1] = E\left[\frac{\beta_1 Cov(X, X)}{Var(X)}\right]
$$

Como $Cov(X, X) = Var(X)$:

$$
E[\hat{\beta}_1] = E\left[\frac{\beta_1 Var(X)}{Var(X)}\right] = E[\beta_1] = \beta_1
$$

---

### Demostración de la varianza de $\hat{\beta}_1$

Escribiendo el estimador en términos de los errores $\varepsilon_i$:

$$
\hat{\beta}_1 = \beta_1 + \frac{\sum_{i=1}^{n}(x_i - \bar{x})\varepsilon_i}{\sum_{i=1}^{n}(x_i - \bar{x})^2}
$$

Aplicando el operador varianza condicional a $X$:

$$
Var(\hat{\beta}_1 | X) = Var\left( \beta_1 + \frac{\sum_{i=1}^{n}(x_i - \bar{x})\varepsilon_i}{\sum_{i=1}^{n}(x_i - \bar{x})^2} \ \Bigg|\  X \right)
$$

Como $\beta_1$ es una constante y asumiendo homocedasticidad ($Var(\varepsilon_i|X) = \sigma^2$) e independencia de los errores:

$$
Var(\hat{\beta}_1 | X) = \frac{\sum_{i=1}^{n}(x_i - \bar{x})^2 Var(\varepsilon_i | X)}{\left(\sum_{i=1}^{n}(x_i - \bar{x})^2\right)^2}
$$

$$
Var(\hat{\beta}_1 | X) = \frac{\sigma^2 \sum_{i=1}^{n}(x_i - \bar{x})^2}{\left(\sum_{i=1}^{n}(x_i - \bar{x})^2\right)^2}
$$ 

Simplificando el término del sumatorio y amplificando todo por $\frac{1}{n}$ tenemos que:

$$
Var(\hat{\beta_1}| X) = \frac{\sigma^2}{nVar(X)}
$$

## Regresión Lineal Múltiple

### Demostración del Estimador del Vector de $\hat{\beta}$ bajo el supuesto de Homocedasticidad

Partimos desde el problema a resolver:

$$
\text{Problema:} \quad \min_{\beta} \xi^T\xi
$$

Sabiendo que $Y = X\beta + \xi$, entonces, $\xi = Y - X\beta$, por tanto el problema se convierte en:

$$
\text{Problema:} \quad \min_{\beta} [Y-X\beta]^T[Y-X\beta]
$$

Por propiedades de matrices, trasponiendo $[Y - X\beta]$ se tiene que:

$$
\text{Problema:} \quad \min_{\beta} [Y^T - \beta^T X^T][Y-X\beta]
$$

Luego, distribuyendo el paréntesis se tiene que:

$$
\text{Problema:} \quad \min_{\beta} Y^TY - Y^TX\beta - \beta^T X^T Y + \beta^T X^T X \beta
$$

Dado que, cada término es igual a un escalar, es decir, una matriz $in \mathbb{M}_1$, entonces un término es igual a su propia transpuesta, por lo que el tercer término queda como:

$$
\text{Problema:} \quad \min_{\beta} Y^TY - Y^TX\beta - Y^TX\beta + \beta^T X^T X \beta
$$

Y por tanto reduciendo queda:

$$
\text{Problema:} \quad \min_{\beta} Y^TY - 2 Y^TX\beta + \beta^T X^T X \beta
$$

Ahora, para minimizar esto, debemos derivar todo con respecto a $\beta$, tal que:

$$
\frac{\partial \xi^T\xi}{\partial \beta} = 0
$$

Donde, derivando obtenemos:

$$
-2X^TY + 2X^TX\hat{\beta} = 0
$$

Factorizando y dividiendo a ambos lados por $2$ tenemos que:

$$
X^TY - X^TX\hat{\beta} = 0
$$
 
Luego, despejamos el término que contiene $\hat{\beta}$:

$$
X^TX\hat{\beta} = X^TY
$$

Utilizando la propiedad $AA^{-1} = I$, entonces multiplicamos a ambos lados **por la izquierda** por $(X^TX)^{-1}$, por lo tanto:

$$
\hat{\beta} = (X^TX)^{-1}X^TY
$$

### Demostración de Insesgadez del Vector de $\hat{\beta}$

Sabemos que el vector de $\hat{\beta}$ está determinado por:

$$
\hat{\beta} = (X^TX)^{-1}X^TY
$$

y sabemos también que $Y = X\beta + \xi$, por lo que al reemplazar:

$$
\hat{\beta} = (X^TX)^{-1}X^T(X\beta + \xi)
$$

aplicando operador de esperanza a ambos lados, condicional a $X$ se tiene que:

$$
E[\hat{\beta}|X] = E[(X^TX)^{-1}X^T(X\beta + \xi)|X]
$$

aplicando propiedad distributiva se tiene que:

$$
E[\hat{\beta}|X] = E[(X^TX)^{-1}X^TX\beta + (X^TX)^{-1}X^T\xi|X]
$$


Ahora, sabiendo dos cosas:

1. $AA^{-1} = I$
2. $E(\xi|X) = 0$

Podemos eliminar el segundo término, pues, es cero y el primer término se reduce a:

$$
E[\hat{\beta}|X] = E[\beta]
$$

Y la esperanza de una constante es simplemente la constante, por lo tanto queda demostrado que el estimador de beta es insesgado:

$$
E[\hat{\beta}|X] = \beta
$$

### Demostración de la Varianza de $\hat{\beta}$ bajo el supuesto de Homocedasticidad

Por definición matricial, la varianza del estimador se puede escribir tal que:

$$
Var(\hat{\beta}|X) = E[\hat{\beta} - \beta][\hat{\beta} - \beta]^T
$$

Si nosotros volvemos hacia atrás sabemos que:

$$
\hat{\beta} = \beta + (X^TX)^{-1}X^T\xi
$$

Por tanto podemos definir que:

$$
\hat{\beta} - \beta = (X^TX)^{-1}X^T\xi
$$

Luego, en la fórmula matricial que definimos para la varianza, tenemos que:

$$
Var(\hat{\beta}|X) = E[(X^TX)^{-1}X^T\xi][(X^TX)^{-1}X^T\xi]^T
$$

Transponiendo el segundo paréntesis se tiene:

$$
Var(\hat{\beta}|X) = E[(X^TX)^{-1}X^T\xi][\xi^TX(X^TX)^{-1}]
$$

Multiplicando:

$$
Var(\hat{\beta}|X) = E[(X^TX)^{-1}X^T\xi\xi^TX(X^TX)^{-1}]
$$

Luego, todo lo que sea $X$ sale del operador de esperanza:

$$
Var(\hat{\beta}|X) = (X^TX)^{-1}X^TE[\xi\xi^T]X(X^TX)^{-1}
$$

Ahora bien, según el supuesto de homocedasticidad de Gauss-Markov $E[\xi\xi^T] = \sigma^2I$, por lo tanto se tiene que:

$$
Var(\hat{\beta}|X) = (X^TX)^{-1}X^T\sigma^2IX(X^TX)^{-1}
$$

Como la multiplicación por la matriz identidad es similar a multiplicar por 1, desaparece. Luego, como $\sigma^2$ es una constante, podemos colocarla hacia el frente, tal que:

$$
Var(\hat{\beta}|X) = \sigma^2(X^TX)^{-1}X^TX(X^TX)^{-1}
$$

Finalmente, usando propiedades de matrices, todo el término se reduce a:

$$
Var(\hat{\beta}|X) = \sigma^2(X^TX)^{-1}
$$

### Demostración de $\tilde{\beta}$

Se formaliza el problema de la siguiente manera:

$$
\text{Problema:} \quad \min_{\beta} \xi^T\xi
$$
$$
\text{s.a} R\beta = q
$$

Donde $R$ es la matriz de coeficientes de las restricciones que queremos estudiar y $q$ es el lado derecho de la restricción.
 Se arma el Lagrangeano de la siguiente manera (Sabiendo que la función objetivo corresponde a algo que hemos visto antes, lo que es $Y^TY - 2 Y^TX\beta + \beta^T X^T X \beta$):

$$
\mathcal{L} =  Y^TY - 2 Y^TX\beta + \beta^T X^T X \beta + 2\lambda^T(R\beta - q)
$$

Luego derivamos con respecto a la variable $\beta$ y a $\lambda$ tal que:

$$
\frac{\partial \mathcal{L}}{\partial \beta} = 0 \land \frac{\partial \mathcal{L}}{\partial \lambda} = 0
$$

Donde la segunda ecuación corresponde a $R\beta = q$, es decir, la restricción. Por otra parte tenemos que:

$$
\frac{\partial \mathcal{L}}{\partial \beta} = -2X^TY + 2X^TX\beta + 2R^T\lambda = 0
$$

Despejando

$$
-X^TY + X^TX\beta + R^T\lambda = 0
$$

$$
X^TX\beta = X^TY -R^T\lambda
$$

Multiplicando por $(X^TX)^{-1}$ por la izquierda obtenemos:

$$
\widetilde{\beta} = (X^TX)^{-1}X^TY - (X^TX)^{-1}R^T\lambda
$$

$$
\widetilde{\beta} = \hat{\beta} - (X^TX)^{-1}R^T\lambda
$$

Luego, para hallar el valor de $\lambda$, mutliplicamos la ecuación obtenida anteriormente por la matriz de restricciones $R$:

$$
R\widetilde{\beta} = R\hat{\beta} - R(X^TX)^{-1}R^T\lambda
$$

Como sabemos que $R\beta = q$ entonces:

$$
q = R\hat{\beta} - R(X^TX)^{-1}R^T\lambda
$$

Despejando:

$$
R(X^TX)^{-1}R^T\lambda = R\hat{\beta} - q 
$$

Como la matriz $R$ tiene rango completo, entonces existe necesariamente la inversa de dicha matriz, por lo tanto:

$$
\lambda = [R(X^TX)^-1R^T]^{-1}(R\hat{\beta}-q)
$$

Sustituyendo $\lambda$ en la primera ecuación, finalmente obtenemos:

$$
\widetilde{\beta} = \hat{\beta} - (X^TX)^{-1}R^T[R(X^TX)^-1R^T]^{-1}(R\hat{\beta}-q)
$$

Donde, en resumidas cuentas, el estimador de MCR es igual al de MCO pero con una corrección proporcional al tamaño del error de la hipótesis. En el supuesto de que, las restricciones fuesen ciertas, entonces esa corrección sería 0 y por lo tanto el estimador de MCR es igual al estimador de MCO.