---
title: "Manual de Econometría I"
author: "Maximiliano Stuardo & Joakina Quezada"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
description: "Manual práctico de Econometría I"
---

bookdown::gitbook:
  css: style.css
  config:
    toc:
      collapse: section
      scroll_highlight: yes
      before: |
        <li><a href="./">Manual de Econometría I</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>
    download: ["pdf", "epub"]
    sharing:
      github: yes
      facebook: no
      twitter: no
    page_navigation: yes

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introducción: ¿Qué es la Econometría? {-}

## Definición de Econometría

La econometría es la disciplina que combina la teoría económica, la estadística y las matemáticas para analizar datos económicos y probar hipótesis. Su objetivo principal es cuantificar relaciones económicas y hacer predicciones basadas en modelos matemáticos.

## Importancia de la Econometría

La importancia de la econometría radica en su capacidad para proporcionar herramientas que permiten a los economistas y analistas tomar decisiones informadas. A través del análisis de datos, la econometría ayuda a:

1. Evaluar políticas económicas.
2. Predecir tendencias económicas.
3. Identificar relaciones causales entre variables económicas.


## Correlación y Causalidad

Es fundamental entender la diferencia entre correlación y causalidad en econometría. La correlación indica que dos variables están relacionadas, pero no necesariamente que una cause la otra. La causalidad, por otro lado, implica que un cambio en una variable provoca un cambio en otra.

Entonces, correlación no implica por ningún motivo causalidad. Por ejemplo, si observamos que el consumo de helado y los casos de insolación aumentan durante el verano, podemos decir que hay una correlación entre estas dos variables. Sin embargo, no podemos concluir que comer helado cause insolación; ambos fenómenos están relacionados con la temporada de verano.